export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const SELECTED_MOVIE = "SELECTED_MOVIE";
export const WATCH_LIST_MOVIE = "WATCH_LIST_MOVIE";
export const REMOVE_MOVIE_FROM_WATCH_LIST = "REMOVE_MOVIE_FROM_WATCH_LIST";